version: 2.1

orbs:
  codacy: codacy/base@0.0.13

jobs:
  build:
    docker:
      #TODO: switch to docker image
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    working_directory: ~/workdir
    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            echo "deb http://download.mono-project.com/repo/debian wheezy main" | tee /etc/apt/sources.list.d/mono-xamarin.list
            apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
            apt-get update
            apt-get install -y mono-complete build-essential nuget unzip
      - attach_workspace:
          at: ~/
      - run:
          name: Compile
          command: |
            make
            make publish
      - persist_to_workspace:
          root: ~/
          paths:
            - workdir

  publish_local:
    machine: true
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Publish tool docker locally
          command: docker build . -t $CIRCLE_PROJECT_REPONAME:latest
      - run:
          name: Save docker to file
          command: |
            mkdir -p workspace
            docker save --output workspace/docker.tar $CIRCLE_PROJECT_REPONAME:latest
      - persist_to_workspace:
          root: workspace
          paths:
            - docker.tar
  # TODO: switch to plugins_test orb
  plugins_test:
    machine: true
    working_directory: ~/
    steps:
      - run:
          name: Clone test project
          command: |
            (git -C ~/codacy-plugins-test fetch --all &&
              git -C ~/codacy-plugins-test reset --hard origin/master) ||
                git clone git://github.com/codacy/codacy-plugins-test.git ~/codacy-plugins-test
      - run:
          name: Generate cache key
          working_directory: ~/codacy-plugins-test
          command: |
            shasum build.sbt \
              project/plugins.sbt \
              project/build.properties \
              project/Common.scala \
              project/Dependencies.scala > /tmp/dependencies.cache.tmp
      - restore_cache:
          key: sbt-ivy2-dependencies-1.0.0-{{ checksum "/tmp/dependencies.cache.tmp" }}
      - run:
          name: Compile test project
          working_directory: ~/codacy-plugins-test
          command: sbt compile
      - save_cache:
          paths:
            - "~/.ivy2"
            - "~/.m2"
            - "~/.sbt"
            - "~/codacy-plugins-test/target"
            - "~/codacy-plugins-test/project/target"
            - "~/codacy-plugins-test/project/project"
          key: sbt-ivy2-dependencies-1.0.0-{{ checksum "/tmp/dependencies.cache.tmp" }}
      - attach_workspace:
          at: ~/
      - run:
          name: Load docker from file
          command: docker load --input docker.tar
      - run:
          name: Test json
          working_directory: ~/codacy-plugins-test
          command: sbt -Dcodacy.tests.ignore.descriptions=false "runMain codacy.plugins.DockerTest json $CIRCLE_PROJECT_REPONAME:latest"
      - run:
          name: Test patterns
          working_directory: ~/codacy-plugins-test
          command: sbt -Dcodacy.tests.noremove=false -Dcodacy.tests.threads=8 "runMain codacy.plugins.DockerTest pattern $CIRCLE_PROJECT_REPONAME:latest"

  publish:
    machine: true
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Load docker from file
          command: docker load --input ~/docker.tar
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME
            docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)
            docker push codacy/$CIRCLE_PROJECT_REPONAME

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - codacy/checkout_and_version
      - build:
          requires:
            - codacy/checkout_and_version
      - publish_local:
          requires:
            - build
      - plugins_test:
          requires:
            - publish_local
      - publish:
          context: CodacyDocker
          filters:
            branches:
              only: master
          requires:
            - plugins_test
      - codacy/tag_version:
          name: tag_version
          requires:
            - publish
